// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDOevchp6WbH76SMMmvs7Ndk8qez37u6n8',
    appId: '1:379516642238:web:4526aff8c3972ca242cfef',
    messagingSenderId: '379516642238',
    projectId: 'test-pro-mobile-app',
    authDomain: 'test-pro-mobile-app.firebaseapp.com',
    storageBucket: 'test-pro-mobile-app.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0LQaRif3j8ggN1wLTV0t97BfQsRvGVDQ',
    appId: '1:379516642238:android:1f2178133292908242cfef',
    messagingSenderId: '379516642238',
    projectId: 'test-pro-mobile-app',
    storageBucket: 'test-pro-mobile-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_TbIOzDevICCqUiOxU18U1bnAmJvNSuE',
    appId: '1:379516642238:ios:e883958fc3d3ba9e42cfef',
    messagingSenderId: '379516642238',
    projectId: 'test-pro-mobile-app',
    storageBucket: 'test-pro-mobile-app.appspot.com',
    iosClientId: '379516642238-4l4s8altfcmies9poto5u67e6s5nem0k.apps.googleusercontent.com',
    iosBundleId: 'com.mehmettalhairmak.TestProMobileApp',
  );
}
